# Generated by Django 5.2 on 2025-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_review_rating'),
        ('myapp', '0006_remove_service_rating_remove_service_review'),
    ]

    operations = [
    ]
