# Generated by Django 5.2 on 2025-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_service_delete_employeedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
