# Generated by Django 5.2 on 2025-04-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_service_rating_service_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='review',
        ),
    ]
